name: Take screenshots

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - uses: actions/github-script@v6
      name: Create shots.yml if missing on first run
      with:
        script: |
          const fs = require('fs');
          if (!fs.existsSync('shots.yml')) {
              const desc = context.payload.repository.description;
              let line = '';
              if (desc && (desc.startsWith('http://') || desc.startsWith('https://'))) {
                  line = `- url: ${desc}` + '\n  output: shot.png\n  height: 800';
              } else {
                  line = '# - url: https://www.example.com/\n#   output: shot.png\n#   height: 800';
              }
              fs.writeFileSync('shots.yml', line + '\n');
          }
    - name: Take shots
      run: |
        shot-scraper multi shots.yml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: shot.png

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')"  >> $GITHUB_OUTPUT
    - name: rename screenshot
      env:
        FILE_NAME: ${{ steps.date.outputs.date }}.png
      run: |-
        mv shot.png $FILE_NAME

    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
  wrangler:
    needs: shot-scraper
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: screenshot

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')"  >> $GITHUB_OUTPUT

      - name: Execute Wrangler Command
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DESTINATION_DIR: test-${{ steps.date.outputs.date }}.png
          BUCKET_NAME: ${{ secrets.R2_BUCKET }}
        run: npx wrangler r2 object put $BUCKET_NAME/$DESTINATION_DIR --file ./shot.png
